name: macOS Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller soundcard

    - name: Build Mac App with PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed --name "DualStream" ui_main.py
        
    - name: Upload Mac App
      uses: actions/upload-artifact@v3
      with:
        name: DualStream-macOS
        path: dist/